[tool.poetry]
name = "interview"
version = "0.1.0"
description = ""
authors = ["iamkhaidarzakirov <root@edu.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
